import org.apache.grails.gradle.publish.GrailsPublishExtension

plugins {
    id 'config.code-coverage'
    id 'config.code-style'
    id 'config.compile'
    id 'config.grails-plugin'
    id 'config.publish'
    id 'config.testing'
}

version = projectVersion
group = 'io.github.gpc'

dependencies {
    profile 'org.apache.grails.profiles:web-plugin'
    console 'org.apache.grails:grails-console'

    compileOnly platform("org.apache.grails:grails-bom:$grailsVersion")
    compileOnly 'org.apache.grails:grails-dependencies-starter-web'

    testImplementation platform("org.apache.grails:grails-bom:$grailsVersion")
    testImplementation 'org.apache.grails:grails-dependencies-starter-web'
    testImplementation 'org.apache.grails:grails-dependencies-test'
}

extensions.configure(GrailsPublishExtension) {
    it.artifactId = 'grails-cookie'
    it.githubSlug = 'gpc/grails-cookie'
    it.websiteUrl = 'https://github.com/gpc/grails-cookie'
    it.license.name = 'Apache-2.0'
    it.title = 'Grails Cookie Plugin'
    it.desc = 'Makes dealing with cookies easy. Provides an injectable service and request/response extensions for one-line cookie get/set/delete. RFC 6265 compliant.'
    it.organization {
        it.name = 'Grails Plugin Consortium'
        it.url = 'https://github.com/gpc'
    }
    it.developers = [
        ctoestreich : 'Christian Oestreich',
        stokito     : 'Sergey Ponomarev',
        dalewiggins : 'Dale Wiggins',
        sbglasius   : 'Søren Berg Glasius',
    ]
}
