---
grails:
  profile: web
  codegen:
    defaultPackage: grails.plugin.cookie.demo
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false

---
grails:
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlets: html
        taglib: none
        staticparts: none
